extramodules patches for clang-16
iso-profiles live-overlay
pamac.conf disable EnableSnap

diff --git a/patches/patch-nvidia-390xx-linux6.5.patch b/patches/patch-nvidia-390xx-linux6.5.patch
--- a/patches/patch-nvidia-390xx-linux6.5.patch
+++ b/patches/patch-nvidia-390xx-linux6.5.patch
@@ -242,17 +242,19 @@ index 0000000..b9c2f8a
 + EXTRA_CFLAGS += $(call cc-option,-Werror=undef,)
 + EXTRA_CFLAGS += -DNV_SPECTRE_V2=$(NV_SPECTRE_V2)
 diff --git a/PKGBUILD b/PKGBUILD
-index 9116fce..9186ca3 100644
+index 15adc76..f3e2b83 100644
 --- a/PKGBUILD
 +++ b/PKGBUILD
-@@ -32,12 +32,16 @@ source=("${_durl}_64/${pkgver}/NVIDIA-Linux-x86_64-${pkgver}-no-compat32.run"
+@@ -32,14 +32,20 @@ source=("${_durl}_64/${pkgver}/NVIDIA-Linux-x86_64-${pkgver}-no-compat32.run"
          'kernel-6.2.patch'
          'kernel-6.3.patch'
          'kernel-6.4.patch'
 +        '001-fix-function-declaration.patch'
 +        '002-Kbuild-clang-options.patch'
          'buildfix_kernel_6.5-garbage-collect-all-references-to-get_user.patch'
-         'buildfix_kernel_6.5-handle-get_user_pages-vmas-argument-remova.patch')
+-        'buildfix_kernel_6.5-handle-get_user_pages-vmas-argument-remova.patch')
++        'buildfix_kernel_6.5-handle-get_user_pages-vmas-argument-remova.patch'
++        'nvidia-graphics-drivers-legacy-390xx-kernel-6.3-with-clang.patch')
  sha256sums=('162317a49aa5a521eb888ec12119bfe5a45cec4e8653efc575a2d04fb05bf581'
              '3501f0bbd9603543da74873905448ff58f5095948a7375617bba74f122d575aa'
              '4284f95f808df4e43afc4632e3fc1f87da1a805f0f6f9af1f6b519c7cf7562b4'
@@ -260,9 +262,13 @@ index 9116fce..9186ca3 100644
 +            'e480e7bd77d7e0e3d5b48282bd2d5ce387564c61c04cfd2287ceb591d191f3cc'
 +            '2da853724551ae20fcfd0026ccd2ebeae5b0602b113eec5c5e7e84e91fd6b10d'
              'b50bfc1f45c706fed3429bf2a876d127405a8a0c7617042ef088ca5493b0814f'
-             'dbb15bb863a74513946738be1ae223f26eab0e631b8ecb05b0f9c52549fdb847')
+-            'dbb15bb863a74513946738be1ae223f26eab0e631b8ecb05b0f9c52549fdb847')
++            'dbb15bb863a74513946738be1ae223f26eab0e631b8ecb05b0f9c52549fdb847'
++            '80549d160b8273e2bbe81d50764161f72d496c677db10364f6d38234105e44f0')
  
-@@ -47,6 +51,8 @@ prepare() {
+ _pkg="NVIDIA-Linux-x86_64-${pkgver}-no-compat32"
+ 
+@@ -47,11 +53,14 @@ prepare() {
      sh "${_pkg}.run" --extract-only
  
      cd "${_pkg}/kernel"
@@ -271,3 +277,108 @@ index 9116fce..9186ca3 100644
      patch -Np1 -i ${srcdir}/kernel-6.2.patch
      patch -Np1 -i ${srcdir}/kernel-6.3.patch
      patch -Np1 -i ${srcdir}/kernel-6.4.patch
+     patch -Np1 -i ${srcdir}/buildfix_kernel_6.5-garbage-collect-all-references-to-get_user.patch
+     patch -Np1 -i ${srcdir}/buildfix_kernel_6.5-handle-get_user_pages-vmas-argument-remova.patch
++    patch -Np1 -i ${srcdir}/nvidia-graphics-drivers-legacy-390xx-kernel-6.3-with-clang.patch
+ }
+ 
+ build() {
+diff --git a/nvidia-graphics-drivers-legacy-390xx-kernel-6.3-with-clang.patch b/nvidia-graphics-drivers-legacy-390xx-kernel-6.3-with-clang.patch
+new file mode 100644
+index 0000000..3ef5996
+--- /dev/null
++++ b/nvidia-graphics-drivers-legacy-390xx-kernel-6.3-with-clang.patch
+@@ -0,0 +1,93 @@
++diff -ur a/conftest.sh b/conftest.sh
++--- a/conftest.sh	2023-06-01 20:00:46.719933661 +0800
+++++ b/conftest.sh	2023-06-01 21:26:23.218584390 +0800
++@@ -255,6 +255,9 @@
++             CFLAGS="$CFLAGS -mfentry -DCC_USING_FENTRY"
++         fi
++     fi
+++
+++    # Warnings
+++    CFLAGS="$CFLAGS -Wno-error=implicit-function-declaration"
++ }
++
++ CONFTEST_PREAMBLE="#include \"conftest/headers.h\"
++@@ -294,6 +297,12 @@
++     echo "$CONFTEST_PREAMBLE
++     $CODE" > conftest$$.c
++
+++    if [ -n "$PRINT" ]; then
+++        >&2 echo "$CONFTEST_PREAMBLE
+++        $CODE"
+++        >&2 echo "$CC $CFLAGS -c conftest$$.c"
+++    fi
+++
++     $CC $CFLAGS -c conftest$$.c > /dev/null 2>&1
++     rm -f conftest$$.c
++
++@@ -860,6 +869,25 @@
++                 return
++             fi
++
+++            echo "$CONFTEST_PREAMBLE
+++            #include <linux/acpi.h>
+++
+++            acpi_op_remove conftest_op_remove_routine;
+++
+++            void conftest_acpi_device_ops_remove(struct acpi_device *device) {
+++                return conftest_op_remove_routine(device);
+++            }" > conftest$$.c
+++
+++            $CC $CFLAGS -c conftest$$.c > /dev/null 2>&1
+++            rm -f conftest$$.c
+++
+++            if [ -f conftest$$.o ]; then
+++                rm -f conftest$$.o
+++                echo "#define NV_ACPI_DEVICE_OPS_REMOVE_ARGUMENT_COUNT 1" | append_conftest "types"
+++                echo "#define NV_ACPI_DEVICE_OPS_REMOVE_VOID_RETURN" | append_conftest "types"
+++                return
+++            fi
+++
++             CODE="
++             #include <linux/acpi.h>
++
++@@ -4765,14 +4812,14 @@
++                 echo "However, mixing compiler versions between the kernel";
++                 echo "and kernel modules can result in subtle bugs that are";
++                 echo "difficult to diagnose.";
++-                echo "";
++-                echo "*** Failed CC version check. Bailing out! ***";
++-                echo "";
+++                # echo "";
+++                # echo "*** Failed CC version check. Bailing out! ***";
+++                # echo "";
++             elif [ "$VERBOSE" = "just_msg" ]; then
++                 echo "The kernel was built with ${kernel_cc_string}, but the" \
++                      "current compiler version is `$CC --version | head -n 1`.";
++             fi
++-            exit 1;
+++            exit 0;
++         fi
++     ;;
++
++diff -ur a/Kbuild b/Kbuild
++--- a/Kbuild	2023-06-01 20:00:46.716600311 +0800
+++++ b/Kbuild	2023-06-01 21:37:31.631878921 +0800
++@@ -68,6 +68,7 @@
++ EXTRA_CFLAGS += $(call cc-option,-Werror=undef,)
++ EXTRA_CFLAGS += -DNV_SPECTRE_V2=$(NV_SPECTRE_V2)
++ EXTRA_CFLAGS += -DNV_KERNEL_INTERFACE_LAYER
+++EXTRA_CFLAGS += -Wno-error=unused-command-line-argument -Wno-error=strict-prototypes
++
++ #
++ # Detect SGI UV systems and apply system-specific optimizations.
++diff -ur a/nvidia-drm/nvidia-drm-fb.c b/nvidia-drm/nvidia-drm-fb.c
++--- a/nvidia-drm/nvidia-drm-fb.c	2023-06-01 20:00:46.723267010 +0800
+++++ b/nvidia-drm/nvidia-drm-fb.c	2023-06-01 21:55:43.793928784 +0800
++@@ -31,6 +31,7 @@
++ #include "nvidia-drm-gem.h"
++ #include "nvidia-drm-helper.h"
++ 
+++#include <drm/drm_modeset_helper.h>
++ #include <drm/drm_crtc_helper.h>
++ 
++ static void nv_drm_framebuffer_destroy(struct drm_framebuffer *fb)
diff --git a/patches/patch-nvidia-470xx-linux6.1.patch b/patches/patch-nvidia-470xx-linux6.1.patch
--- a/patches/patch-nvidia-470xx-linux6.1.patch
+++ b/patches/patch-nvidia-470xx-linux6.1.patch
@@ -265,29 +265,117 @@ index 0000000..fda2cea
 + {
 +     if (!g_uvm_perf_prefetch_enable)
 +         return;
+diff --git a/002-Kbuild-clang-options.patch b/002-Kbuild-clang-options.patch
+new file mode 100644
+index 0000000..a94f392
+--- /dev/null
++++ b/002-Kbuild-clang-options.patch
+@@ -0,0 +1,13 @@
++diff --git a/kernel/Kbuild b/kernel/Kbuild
++index e160e3a..9a9419d 100644
++--- a/kernel/Kbuild
+++++ b/kernel/Kbuild
++@@ -68,7 +68,7 @@ $(foreach _module, $(NV_KERNEL_MODULES), \
++ 
++ EXTRA_CFLAGS += -I$(src)/common/inc
++ EXTRA_CFLAGS += -I$(src)
++-EXTRA_CFLAGS += -Wall -MD $(DEFINES) $(INCLUDES) -Wno-cast-qual -Wno-error -Wno-format-extra-args
+++EXTRA_CFLAGS += -Wall $(DEFINES) $(INCLUDES) -Wno-cast-qual -Wno-error -Wno-format-extra-args -Wno-error=implicit-function-declaration
++ EXTRA_CFLAGS += -D__KERNEL__ -DMODULE -DNVRM -DNV_VERSION_STRING=\"470.199.02\" -Wno-unused-function -Wuninitialized -fno-strict-aliasing -mno-red-zone -mcmodel=kernel -DNV_UVM_ENABLE
++ EXTRA_CFLAGS += $(call cc-option,-Werror=undef,)
++ EXTRA_CFLAGS += -DNV_SPECTRE_V2=$(NV_SPECTRE_V2)
 diff --git a/PKGBUILD b/PKGBUILD
-index 7405cb0..d6ec744 100644
+index 51b6aa1..39863a4 100644
 --- a/PKGBUILD
 +++ b/PKGBUILD
-@@ -20,8 +20,11 @@ provides=("nvidia=$pkgver" 'NVIDIA-MODULE')
+@@ -20,16 +20,25 @@ provides=("nvidia=$pkgver" 'NVIDIA-MODULE')
  options=(!strip)
  install=nvidia.install
  _durl="https://us.download.nvidia.com/XFree86/Linux-x86"
 -source=("${_durl}_64/${pkgver}/NVIDIA-Linux-x86_64-${pkgver}-no-compat32.run")
 -sha256sums=('9c86f9ef6aceaf2b292407aa161b98d817b2eb10a615f971d29a20c2a748ad09')
 +source=("${_durl}_64/${pkgver}/NVIDIA-Linux-x86_64-${pkgver}-no-compat32.run"
-+        001-fix-function-declaration.patch)
++        '001-fix-function-declaration.patch'
++        '002-Kbuild-clang-options.patch'
++        'nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch')
 +sha256sums=('9c86f9ef6aceaf2b292407aa161b98d817b2eb10a615f971d29a20c2a748ad09'
 +            '8e9bcc9c3f68771de87da73b0837095f84e2f2abb6dd0bdaa2117c95ae118c3a'
-+)
++            '32318fff83e5a989ba163e40be7e5491a7ca01a609650782021c61fbfd1d2622'
++            '702af56eef8bba8c3137f98c298ee204e391c6fcffc960631481c3f1e87ed6a8')
  
  _pkg="NVIDIA-Linux-x86_64-${pkgver}-no-compat32"
  
-@@ -30,6 +33,7 @@ prepare() {
+ prepare() {
+     sh "${_pkg}.run" --extract-only
  
-     cd "${_pkg}"
+-    cd "${_pkg}"
++    cd "${_pkg}/kernel"
      # patches here
-+    patch -p1 -i ${srcdir}/001-fix-function-declaration.patch
++    patch -p2 -i ${srcdir}/001-fix-function-declaration.patch
++    patch -p2 -i ${srcdir}/002-Kbuild-clang-options.patch
++    patch -p1 -i ${srcdir}/nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch
  }
  
  build() {
+diff --git a/nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch b/nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch
+new file mode 100644
+index 0000000..8e33ba5
+--- /dev/null
++++ b/nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch
+@@ -0,0 +1,56 @@
++diff -ur a/conftest.sh b/conftest.sh
++--- a/conftest.sh	2023-06-01 20:00:46.719933661 +0800
+++++ b/conftest.sh	2023-06-01 21:26:23.218584390 +0800
++@@ -255,6 +255,9 @@
++             CFLAGS="$CFLAGS -mfentry -DCC_USING_FENTRY"
++         fi
++     fi
+++
+++    # Warnings
+++    CFLAGS="$CFLAGS -Wno-error=implicit-function-declaration"
++ }
++
++ CONFTEST_PREAMBLE="#include \"conftest/headers.h\"
++@@ -294,6 +297,12 @@
++     echo "$CONFTEST_PREAMBLE
++     $CODE" > conftest$$.c
++
+++    if [ -n "$PRINT" ]; then
+++        >&2 echo "$CONFTEST_PREAMBLE
+++        $CODE"
+++        >&2 echo "$CC $CFLAGS -c conftest$$.c"
+++    fi
+++
++     $CC $CFLAGS -c conftest$$.c > /dev/null 2>&1
++     rm -f conftest$$.c
++
++@@ -4765,14 +4812,14 @@
++                 echo "However, mixing compiler versions between the kernel";
++                 echo "and kernel modules can result in subtle bugs that are";
++                 echo "difficult to diagnose.";
++-                echo "";
++-                echo "*** Failed CC version check. Bailing out! ***";
++-                echo "";
+++                # echo "";
+++                # echo "*** Failed CC version check. Bailing out! ***";
+++                # echo "";
++             elif [ "$VERBOSE" = "just_msg" ]; then
++                 echo "The kernel was built with ${kernel_cc_string}, but the" \
++                      "current compiler version is `$CC --version | head -n 1`.";
++             fi
++-            exit 1;
+++            exit 0;
++         fi
++     ;;
++
++diff -ur a/Kbuild b/Kbuild
++--- a/Kbuild	2023-06-01 20:00:46.716600311 +0800
+++++ b/Kbuild	2023-06-01 21:37:31.631878921 +0800
++@@ -68,6 +68,7 @@
++ EXTRA_CFLAGS += $(call cc-option,-Werror=undef,)
++ EXTRA_CFLAGS += -DNV_SPECTRE_V2=$(NV_SPECTRE_V2)
++ EXTRA_CFLAGS += -DNV_KERNEL_INTERFACE_LAYER
+++EXTRA_CFLAGS += -Wno-error=unused-command-line-argument -Wno-error=strict-prototypes
++
++ #
++ # Detect SGI UV systems and apply system-specific optimizations.
