patches
patch-nvidia-470xx
clang-16

diff --git a/patches/patch-nvidia-470xx-linux6.5.patch b/patches/patch-nvidia-470xx-linux6.5.patch
--- a/patches/patch-nvidia-470xx-linux6.5.patch
+++ b/patches/patch-nvidia-470xx-linux6.5.patch
@@ -280,34 +280,99 @@ index 0000000..f3b118a
 + EXTRA_CFLAGS += -I$(src)/common/inc
 + EXTRA_CFLAGS += -I$(src)
 +-EXTRA_CFLAGS += -Wall -MD $(DEFINES) $(INCLUDES) -Wno-cast-qual -Wno-error -Wno-format-extra-args
-++EXTRA_CFLAGS += -Wall $(DEFINES) $(INCLUDES) -Wno-cast-qual -Wno-error -Wno-format-extra-args -Wno-error=implicit-function-declaration
+++EXTRA_CFLAGS += -Wall $(DEFINES) $(INCLUDES) -Wno-cast-qual -Wno-error -Wno-format-extra-args
 + EXTRA_CFLAGS += -D__KERNEL__ -DMODULE -DNVRM -DNV_VERSION_STRING=\"470.199.02\" -Wno-unused-function -Wuninitialized -fno-strict-aliasing -mno-red-zone -mcmodel=kernel -DNV_UVM_ENABLE
 + EXTRA_CFLAGS += $(call cc-option,-Werror=undef,)
 + EXTRA_CFLAGS += -DNV_SPECTRE_V2=$(NV_SPECTRE_V2)
 diff --git a/PKGBUILD b/PKGBUILD
-index cbc38e4..4527ce9 100644
+index 386346c..85a1466 100644
 --- a/PKGBUILD
 +++ b/PKGBUILD
-@@ -22,9 +22,13 @@ options=(!strip)
+@@ -22,9 +22,15 @@ options=(!strip)
  install=nvidia.install
  _durl="https://us.download.nvidia.com/XFree86/Linux-x86"
  source=("${_durl}_64/${pkgver}/NVIDIA-Linux-x86_64-${pkgver}-no-compat32.run"
 +        '001-fix-function-declaration.patch'
 +        '002-Kbuild-clang-options.patch'
++        'nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch'
          'kernel-6.4.patch'
          'kernel-6.5.patch')
  sha256sums=('9c86f9ef6aceaf2b292407aa161b98d817b2eb10a615f971d29a20c2a748ad09'
 +            'b8971052d71cfafc80ce2e13d4c3d09ffe6e82864b3bdfb6daf5de26e51d7ff7'
-+            '32318fff83e5a989ba163e40be7e5491a7ca01a609650782021c61fbfd1d2622'
++            'd75c572230b68d5d0663805ac7a22dce95ec193e14bed9229cc26b790bc33d4e'
++            '702af56eef8bba8c3137f98c298ee204e391c6fcffc960631481c3f1e87ed6a8'
              '9fbab269f00beb78b44e4693ea44b399e4122a3dfba00322af3e5e3485a1eed3'
              '8688f9d70b34e8111722c0231f773050a62a5d1c1b56c88aa3bab8ebf502902a')
  
-@@ -34,6 +38,8 @@ prepare() {
+@@ -34,6 +40,9 @@ prepare() {
      sh "${_pkg}.run" --extract-only
  
      cd "${_pkg}/kernel"
 +    patch -p2 -i ${srcdir}/001-fix-function-declaration.patch
 +    patch -p2 -i ${srcdir}/002-Kbuild-clang-options.patch
++    patch -p1 -i ${srcdir}/nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch
      # patches here
      patch -Np1 -i ../../kernel-6.4.patch
      patch -Np1 -i ../../kernel-6.5.patch
+diff --git a/nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch b/nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch
+new file mode 100644
+index 0000000..8e33ba5
+--- /dev/null
++++ b/nvidia-graphics-drivers-legacy-470xx-with-clang-16.patch
+@@ -0,0 +1,56 @@
++diff -ur a/conftest.sh b/conftest.sh
++--- a/conftest.sh	2023-06-01 20:00:46.719933661 +0800
+++++ b/conftest.sh	2023-06-01 21:26:23.218584390 +0800
++@@ -255,6 +255,9 @@
++             CFLAGS="$CFLAGS -mfentry -DCC_USING_FENTRY"
++         fi
++     fi
+++
+++    # Warnings
+++    CFLAGS="$CFLAGS -Wno-error=implicit-function-declaration"
++ }
++
++ CONFTEST_PREAMBLE="#include \"conftest/headers.h\"
++@@ -294,6 +297,12 @@
++     echo "$CONFTEST_PREAMBLE
++     $CODE" > conftest$$.c
++
+++    if [ -n "$PRINT" ]; then
+++        >&2 echo "$CONFTEST_PREAMBLE
+++        $CODE"
+++        >&2 echo "$CC $CFLAGS -c conftest$$.c"
+++    fi
+++
++     $CC $CFLAGS -c conftest$$.c > /dev/null 2>&1
++     rm -f conftest$$.c
++
++@@ -4765,14 +4812,14 @@
++                 echo "However, mixing compiler versions between the kernel";
++                 echo "and kernel modules can result in subtle bugs that are";
++                 echo "difficult to diagnose.";
++-                echo "";
++-                echo "*** Failed CC version check. Bailing out! ***";
++-                echo "";
+++                # echo "";
+++                # echo "*** Failed CC version check. Bailing out! ***";
+++                # echo "";
++             elif [ "$VERBOSE" = "just_msg" ]; then
++                 echo "The kernel was built with ${kernel_cc_string}, but the" \
++                      "current compiler version is `$CC --version | head -n 1`.";
++             fi
++-            exit 1;
+++            exit 0;
++         fi
++     ;;
++
++diff -ur a/Kbuild b/Kbuild
++--- a/Kbuild	2023-06-01 20:00:46.716600311 +0800
+++++ b/Kbuild	2023-06-01 21:37:31.631878921 +0800
++@@ -68,6 +68,7 @@
++ EXTRA_CFLAGS += $(call cc-option,-Werror=undef,)
++ EXTRA_CFLAGS += -DNV_SPECTRE_V2=$(NV_SPECTRE_V2)
++ EXTRA_CFLAGS += -DNV_KERNEL_INTERFACE_LAYER
+++EXTRA_CFLAGS += -Wno-error=unused-command-line-argument -Wno-error=strict-prototypes
++
++ #
++ # Detect SGI UV systems and apply system-specific optimizations.
